### PR TITLE
adding dot

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
@brianmcarey 
Hey Brain do you know why the unit test job doesn't run

**Comment by brianmcarey** [comment]
> @brianmcarey Hey Brain do you know why the unit test job doesn't run

It can take a minute or two for the new job configs to be applied to the cluster and for github PR status to sync.

**Comment by brianmcarey** [comment]
> > @brianmcarey Hey Brain do you know why the unit test job doesn't run
> 
> It can take a minute or two for the new job configs to be applied to the cluster and for github PR status to sync.

Also the PR is not yet merged - just approved

**Comment by Barakmor1** [comment]
Your right :)
Sorry for the rush.

**Pull request merged**
